import { z } from "zod";

export const RepoSchema = z.object({
	id: z.number(),
	node_id: z.string(),
	name: z.string(),
	full_name: z.string(),
	private: z.boolean(),
	owner: z.object({
		login: z.string(),
		id: z.number(),
	}),
	html_url: z.string().url(),
	description: z.string().nullable(),
	fork: z.boolean(),
	url: z.string().url(),
	created_at: z.string(),
	updated_at: z.string(),
	pushed_at: z.string(),
	git_url: z.string(),
	ssh_url: z.string(),
	clone_url: z.string(),
	svn_url: z.string(),
	homepage: z.string().nullable(),
	stargazers_count: z.number(),
	watchers_count: z.number(),
	language: z.string().nullable(),
	has_issues: z.boolean(),
	has_projects: z.boolean(),
	has_downloads: z.boolean(),
	has_wiki: z.boolean(),
	has_pages: z.boolean(),
	forks_count: z.number(),
	mirror_url: z.string().url().nullable(),
	archived: z.boolean(),
	disabled: z.boolean(),
	open_issues_count: z.number(),
	license: z.object({
		key: z.string(),
		name: z.string(),
		spdx_id: z.string(),
		url: z.string().url().nullable(),
		node_id: z.string(),
	}).nullable(),
	allow_forking: z.boolean(),
	is_template: z.boolean(),
	topics: z.array(z.string()),
	visibility: z.string(),
	forks: z.number(),
	open_issues: z.number(),
	watchers: z.number(),
	default_branch: z.string(),
});

export type Repo = z.infer<typeof RepoSchema>;

export const UserSchema = z.object({
	login: z.string(),
	id: z.number(),
	node_id: z.string(),
	avatar_url: z.string().url(),
	gravatar_id: z.string(),
	url: z.string().url(),
	html_url: z.string().url(),
	followers_url: z.string().url(),
	following_url: z.string().url(),
	gists_url: z.string().url(),
	starred_url: z.string().url(),
	subscriptions_url: z.string().url(),
	organizations_url: z.string().url(),
	repos_url: z.string().url(),
	events_url: z.string().url(),
	received_events_url: z.string().url(),
	type: z.string(),
	site_admin: z.boolean(),
	name: z.string().nullable(),
	company: z.string().nullable(),
	blog: z.string(),
	location: z.string().nullable(),
	email: z.string().email().nullable(),
	hireable: z.boolean().nullable(),
	bio: z.string().nullable(),
	twitter_username: z.string().nullable(),
	public_repos: z.number(),
	public_gists: z.number(),
	followers: z.number(),
	following: z.number(),
	created_at: z.string(),
	updated_at: z.string(),
});

export type User = z.infer<typeof UserSchema>;

export const IssueSchema = z.object({
	id: z.number(),
	node_id: z.string(),
	url: z.string().url(),
	repository_url: z.string().url(),
	labels_url: z.string().url(),
	comments_url: z.string().url(),
	events_url: z.string().url(),
	html_url: z.string().url(),
	number: z.number(),
	state: z.string(),
	title: z.string(),
	body: z.string().nullable(),
	user: UserSchema.pick({ login: true, id: true, avatar_url: true, html_url: true }),
	labels: z.array(z.object({
		id: z.number(),
		node_id: z.string(),
		url: z.string().url(),
		name: z.string(),
		color: z.string(),
		default: z.boolean(),
		description: z.string().nullable(),
	})),
	assignee: UserSchema.pick({ login: true, id: true, avatar_url: true, html_url: true }).nullable(),
	assignees: z.array(UserSchema.pick({ login: true, id: true, avatar_url: true, html_url: true })).nullable(),
	milestone: z.object({
		url: z.string().url(),
		html_url: z.string().url(),
		labels_url: z.string().url(),
		id: z.number(),
		node_id: z.string(),
		number: z.number(),
		title: z.string(),
		description: z.string().nullable(),
		creator: UserSchema.pick({ login: true, id: true }),
		open_issues: z.number(),
		closed_issues: z.number(),
		state: z.string(),
		created_at: z.string(),
		updated_at: z.string(),
		due_on: z.string().nullable(),
		closed_at: z.string().nullable(),
	}).nullable(),
	locked: z.boolean(),
	active_lock_reason: z.string().nullable(),
	comments: z.number(),
	pull_request: z.object({
		url: z.string().url(),
		html_url: z.string().url(),
		diff_url: z.string().url(),
		patch_url: z.string().url(),
	}).optional(),
	closed_at: z.string().nullable(),
	created_at: z.string(),
	updated_at: z.string(),
	author_association: z.string(),
});

export type Issue = z.infer<typeof IssueSchema>;
